"""empty message

Revision ID: 087197d99e37
Revises: 
Create Date: 2023-07-19 12:21:10.126129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087197d99e37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sciences',
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('last_login', sa.String(length=50), nullable=True),
    sa.Column('joined', sa.String(length=50), nullable=True),
    sa.Column('is_stuff', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('categories',
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=100), nullable=True),
    sa.Column('science_id', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['science_id'], ['sciences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('problems',
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('time_asked', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_answered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('science_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['science_id'], ['sciences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formulas',
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('formula', sa.String(length=40), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('problemmedias',
    sa.Column('problem_id', sa.String(length=100), nullable=True),
    sa.Column('media_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solutions',
    sa.Column('author_id', sa.String(length=100), nullable=True),
    sa.Column('problem_id', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('formula_id', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('formula_url', sa.String(length=50), nullable=True),
    sa.Column('date_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solutionmedias',
    sa.Column('solution_id', sa.String(length=100), nullable=True),
    sa.Column('media_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solutionmedias')
    op.drop_table('history')
    op.drop_table('solutions')
    op.drop_table('problemmedias')
    op.drop_table('formulas')
    op.drop_table('problems')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('sciences')
    # ### end Alembic commands ###
