"""empty message

Revision ID: 23c6541c93df
Revises: 7020533232be
Create Date: 2023-07-17 23:19:43.115576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c6541c93df'
down_revision = '7020533232be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('title', sa.String(length=40), nullable=True))
    op.drop_constraint('categories_category_name_key', 'categories', type_='unique')
    op.create_unique_constraint(None, 'categories', ['title'])
    op.drop_column('categories', 'category_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_unique_constraint('categories_category_name_key', 'categories', ['category_name'])
    op.drop_column('categories', 'title')
    # ### end Alembic commands ###
