"""empty message

Revision ID: 273df632e57f
Revises: f33e63753166
Create Date: 2023-07-23 13:36:53.898680

"""
from alembic import op
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision = '273df632e57f'
down_revision = 'f33e63753166'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'problems', 'solutions', ['solution_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='foreignkey')
    # ### end Alembic commands ###
