"""empty message

Revision ID: 7020533232be
Revises: 
Create Date: 2023-07-17 13:37:39.785325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7020533232be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sciences',
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('auth',
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('last_login', sa.String(length=50), nullable=True),
    sa.Column('joined', sa.String(length=50), nullable=True),
    sa.Column('is_stuff', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('categories',
    sa.Column('category_name', sa.String(length=40), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('science_id', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['science_id'], ['sciences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('history',
    sa.Column('formula', sa.String(length=40), nullable=True),
    sa.Column('result', sa.String(length=40), nullable=True),
    sa.Column('formula_url', sa.String(length=50), nullable=True),
    sa.Column('date_time', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formulas',
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('formula', sa.String(length=40), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formulas')
    op.drop_table('history')
    op.drop_table('categories')
    op.drop_table('auth')
    op.drop_table('sciences')
    # ### end Alembic commands ###
