"""empty message

Revision ID: 912ffc5225f4
Revises: 
Create Date: 2023-07-18 11:30:15.142362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912ffc5225f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
